#!/bin/bash
battery() {
	BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`
    cat /sys/class/power_supply/${BAT}/capacity
}
battery_stat() {

	BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`
	bs=$(cat /sys/class/power_supply/${BAT}/status)
    if [ "$bs" = "Discharging" ] ; then
        echo ""
    elif [ "$bs" = "Full" ] ; then
        echo ""
    elif [ "$bs" = "Charging" ] ; then
        echo ""
    fi
}
if [ "$1" = "-p" ] ; then
    battery
elif [ "$1" = "-s" ] ; then
    battery_stat
fi
